version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - goconst
    - gocritic
    - revive
    - gosec
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
        - exposedSyncMutex
        - importShadow
    gosec:
      severity: medium
      confidence: medium
    govet:
      enable-all: true
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
        - name: var-naming
          severity: warning
          disabled: false
        - name: var-declaration
          severity: warning
          disabled: false
        - name: package-comments
          severity: warning
          disabled: false
        - name: range
          severity: warning
          disabled: false
        - name: increment-decrement
          severity: warning
          disabled: false
        - name: error-return
          severity: warning
          disabled: false
    staticcheck:
      checks: ["all"]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
