version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gocritic
    - revive
    - gosec
  disable:
    - errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
